config/routes.rb
Rails.application.routes.draw do

  root to: 'site#home'

  resources :users do
    resources :flats do
      resources :rooms
    end
  end

  get '/match/show' => 'matches#show'

end

app/models/flat.rb
class Flat < ActiveRecord::Base
	attr_accessor :flat_photo_file_name

	has_many :rooms
	belongs_to :user

	validates :user_id, uniqueness: true
	validates :num_rooms, presence: true
	validates :num_baths, presence: true
	validates :area, presence: true
	validates_inclusion_of :pet, :in => [true, false]
	validates_presence_of :user

	has_attached_file :flat_photo, :styles => { :large => "120x120>", :medium => "48x48>", :thumb => "26x26>" }
	validates_attachment_content_type :flat_photo, :content_type => /\Aimage\/.*\Z/
end

app/models/match.rb
class Match
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :percentage, :user_id, :room_id

  belongs_to :user

end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :flat

	validates :price, presence: true

	has_attached_file :room_photo, :styles => { :large => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :room_photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :flat
  has_many :matches

	validates :name, presence: true
	validates :email, presence: true

	has_attached_file :avatar, :styles => { :large => "120x120>", :medium => "48x48>", :thumb => "26x26>" }
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
	def index
		@user =  User.find params[:user_id]
		@flat = @user.flat
	end

	def new
		@flat = Flat.new
		@user =  User.find params[:user_id]
		render :layout => 'form'
	end

	def create
		@flat = Flat.new flat_params
		@user =  User.find params[:user_id]

		if @flat.save
			flash[:notice] = "Flat created successfully"
			redirect_to user_flat_path(@user.id, @flat.id)
		else
			flash[:alert] = "Something went wrong :("
			render 'new'
		end
	end

	def show
		@user =  User.find params[:user_id]
		@flat = Flat.find params[:id]
		render :layout => 'form'
	end

	def edit
		@user =  User.find params[:user_id]
		@flat = @user.flat
		render :layout => 'form'
	end

	def update
		@flat = Flat.find params[:id]

		if @flat.update_attributes flat_params
			redirect_to action: :show, controller: :flats, id: @flat.id
		else
			render 'flat'
		end
	end

	def destroy
		@flat = Flat.find params[:id]

		if @flat.destroy
			redirect_to action: :show, controller: :users, id: params[:user_id]
		else
			redirect_to :back
		end
	end

	private

	def flat_params
		params.require(:flat).permit(:num_rooms,:num_baths,:pet,:area,:flat_photo,:user_id)
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def choose_search_parameters

  end

  def perform_search
    # see how many search parameters are filled

    # filter
    @results = Room.all

    if params[:num_rooms]
      @results = @results.where(num_rooms: params[:num_rooms])
    end
    if params[:num_baths]
      @results = @results.where(num_baths: params[:num_baths])
    end
    if params[:price]
      @results = @results.where(price: params[:price])
    end
    if params[:pet]
      @results = @results.where(pet: params[:pet])
    end
    if params[:area]
      @results = @results.where(area: params[:area])
    end

    # for each result shown calculate its percentage
    render 'show'
  end

  def show
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	def index
		@user_id = params[:user_id]
		@flat =  Flat.find params[:flat_id]
		@rooms = @flat.rooms
		render :layout => 'center_content'
	end

	def new
		@room = Room.new
		@user =  User.find params[:user_id]
		@flat =  Flat.find params[:flat_id]
		render :layout => 'form'
	end

	def create
		@room = Room.new room_params
		user_id = params[:user_id]
		flat_id = params[:flat_id]

		if @room.save
			flash[:notice] = "room created successfully"
			redirect_to user_flat_rooms_path(user_id, flat_id)
		else
			flash[:alert] = "Something went wrong :("
			render 'new'
		end
	end

	def edit
    @user =  User.find params[:user_id]
    @flat =  Flat.find params[:flat_id]
    @room = Room.find params[:id]
    render :layout => 'form'
	end

	def update
		user_id = params[:user_id]
		flat_id = params[:flat_id]
		@room = Room.find params[:id]

		if @room.update_attributes room_params
			redirect_to user_flat_rooms_path(user_id, flat_id)
		else
			render 'edit'
		end
	end

	def destroy
		@room = Room.find params[:id]

		if @room.destroy
			redirect_to action: 'index'
		else
			redirect_to :back
		end
	end

	private

	def room_params
		params.require(:room).permit(:room_photo,:price,:flat_id)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
		render :layout => 'form'
	end

	def create
		@user = User.new user_params

		if @user.save
			flash[:notice] = "User created successfully"
			redirect_to user_path(@user.id)
		else
			flash[:alert] = "Something went wrong :("
			render 'new'
		end
	end

	def show
		@user = User.find params[:id]
		render :layout => 'form'
	end

	def edit
		@user = User.find params[:id]
		render :layout => 'form'
	end

	def update
		@user = User.find params[:id]

		if @user.update_attributes user_params
			redirect_to action: :show, controller: :users, id: @user.id
		else
			render 'user'
		end
	end

	def destroy
		@user = User.find params[:id]

		if @user.destroy
			redirect_to action: 'index'
		else
			redirect_to :back
		end
	end

	private

	def user_params
		params.require(:user).permit(:name,:email,:avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/flats/_form.html.erb
<div class= "bg_color padd_20">

	<%= form_for [@user, @flat] do |f| %>
		<%= f.hidden_field :user_id, :value => @user.id %>

		<%= f.label :flat_photo %> (optinal)
		<%= f.file_field :flat_photo, class: "form-control" %>
		<br />
		<%= f.label :num_rooms %>
		<%= f.number_field :num_rooms, placeholder: 'Write number of rooms', class: "form-control", in: 1..6, step:1  %>
		<br />
		<%= f.label :num_baths %>
		<%= f.number_field :num_baths, placeholder: 'Write number of baths', class: "form-control", in: 1..6, step:1  %>
		<br />
		<%= f.label :pet %>
		<br/>
		<%= f.radio_button(:pet, 'true') %>  Accepted!
		<%= f.radio_button(:pet, 'false') %>  Not accepted!
		<br/>
		<br/>
		<%= f.label :area %>
		<%= f.select :area, ['Eixample', 'Sants', 'Poble Nou', 'Gràcia', 'Raval', 'Gotic', 'Sarria', 'Barceloneta'], {}, {:class => 'form-control mtop'}%>
		<br/>
		<%= f.submit 'SAVE', class: "btn btn_form btn-lg btn-block" %>
	<% end %>
</div>

app/views/flats/edit.html.erb
<div class= "center_form">
  <div class= "form_group">
    <h2 class= "col-md-3 col-md-offset-5 bg_new_color arrow arrow-s desc"> Edit Flat </h2>
    <%= render 'form' %>
  </div>
</div>

app/views/flats/index.html.erb
<div class= "center_form">
	<h2 class= "col-md-3 col-md-offset-5 bg_new_color arrow arrow-s desc">
		Flats list
	</h2>

	<div class=" col-md-3 col-md-offset-5 bg_color contenido">
		<ul>
			<li>
				<%= @flat.flat_photo %>
				<%= @flat.num_rooms %>
				<%= @flat.num_baths %>
				<%= @flat.pet %>
				<%= @flat.area %>
			</li>
		</ul>

		<%= link_to('Delete', user_flat_path(@user.id, @flat), method: :delete, data: { confirm: 'Are you sure' }) %>
		<br/>
		<%= link_to 'new room', new_user_flat_room_path(@user.id, @flat) %>
	</div>
</div>

app/views/flats/new.html.erb
<h2 class= "bg_new_color arrow arrow-s desc"> Create a new Flat </h2>
<%= render 'form' %>

app/views/flats/show.html.erb
<h2 class= "bg_new_color arrow arrow-s desc">
	Flat information
</h2>

<div class="bg_color padd_20">
	<ul>
		<li>Rooms number: <strong><%= @flat.num_rooms %></strong> </li>
		<li>Baths number: <strong><%= @flat.num_baths %></strong> </li>
		<li>Pets: <strong><%= @flat.pet %></strong> </li>
		<li>Area: <strong><%= @flat.area %></strong> </li>
	</ul>

	<div class="opciones">
		<%= link_to 'EDIT FLAT', edit_user_flat_path(@user.id, @flat.id), class: "btn btn_form mb_10 width_202" %>
		<%= link_to 'CREATE A ROOM', new_user_flat_room_path(@user.id, @flat.id), class: "btn btn_form mb_10 width_202" %>
		<%= link_to 'DELETE FLAT', user_flat_path(@user.id, @flat), method: :delete, class: "btn btn_form width_202 btn-danger", confirm: "Are you sure?" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matchaflat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.ico">
</head>

<body>

<%= yield %>

</body>
</html>

app/views/layouts/form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matchaflat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="favicon.ico">
</head>
<body class = "bg_img">
<nav class="nav-general">
  <div class="ml">
    <a href="/" class="hamb fleft"><img src= "<%= image_path("hamburguer2.png")%>" alt="Hamburguer menu" class="hamb"></a>
  </div>
  <div class="centrado dis-block ">
    <a href="/" class="">
      <img src= "<%= image_path("logo_roommate2.png")%>" alt="Logo Hotel" class="logo " >
    </a>
  </div>

  <div class="menu_right">
    <%= link_to 'SIGNUP', new_user_path, class: "btn btn_box btn_intro2 fright fri2" %>
    <%= link_to 'LOGIN', new_user_path, class: "btn btn_box btn_intro2 fright" %>
  </div>
</nav>

<div class="container">
  <div class="row row-centered">
    <div class=" col-md-3 col-centered top_100">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/matches/show.html.erb
<nav class="nav-general bg-white">
  <div class="ml">
    <a href="/" class="hamb fleft"><img src= "<%= image_path("hamburguer.png")%>" alt="Hamburguer menu" class="hamb"></a>
  </div>
  <div class="centrado dis-block ">
    <a href="/" class="">
      <img src= "<%= image_path("logo_roommate.png")%>" alt="Logo Hotel" class="logo " >
    </a>
  </div>

  <div class="menu_right">
    <%= link_to 'SIGNUP', new_user_path, class: "btn btn_box  btn_intro fright fri2" %>
    <%= link_to 'LOGIN', new_user_path, class: "btn btn_box btn_intro fright" %>
  </div>

</nav>

<main>
  <section class="match">
    <div class= "bg_img_match">

    </div>
  </section>
</main>

app/views/rooms/_form.html.erb
<div class= "bg_color padd_20">
	<%= form_for [@user, @flat, @room] do |f| %>
		<%= f.hidden_field :flat_id, :value => @flat.id %>

		<%= f.label :room_photo %> (optinal)
		<%= f.file_field :room_photo, class: "form-control" %>
		<br />
		<%= f.label :price %>
		<%= f.number_field :price, class: "form-control mb",  step: 10 %>

		<%= f.submit 'SAVE', class: "btn btn_form btn-lg btn-block" %>
	<% end %>
</div>

app/views/rooms/edit.html.erb
<h2 class= "bg_new_color arrow arrow-s desc"> Edit Room </h2>
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class= "col-centered relative">
  <h2 class= "bg_new_color row arrow arrow-s desc">Rooms list</h2>
  <% if @flat.num_rooms > @flat.rooms.count %>
    <%= link_to '+ ADD', new_user_flat_room_path(@user_id, @flat.id), class: "btn absolute bg_create" %>
  <% end %>
  <div class= "bg_color padding-top10 row">
    <ul class="padding0">
      <% @rooms.each do |room| %>
        <li class= "col-md-6 width each_room margin20 padding0">
        <% if room.room_photo%>
          <%= image_tag room.room_photo.url(:large), class: "room_img"%>
        <% end %>
        </br>
        <p class="margin_left10">
          Price: <strong><%= room.price %> €</strong>
        </p>

        <%= link_to 'EDIT ROOM', edit_user_flat_room_path(@user_id, @flat.id, room.id), class: "btn btn_form mb_10 padding_sides margin_left10"%>
        <%= link_to 'DELETE ROOM', user_flat_room_path(@user_id, @flat.id, room.id), method: :delete, class: "btn btn_form mb_10 padding_sides", data: { confirm: 'Are you sure' } %>
        <%= link_to 'SHOW MATCH', match_show_path, class: "btn btn_form mb_10 margin_left10 width280"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/rooms/new.html.erb
<h2 class= "bg_new_color arrow arrow-s desc"> Create a new room </h2>
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="center_form">
  <div class= "col-md-8 col-md-offset-2 bg_new_color arrow arrow-s desc">
    <h2 class= "desc pad_0">Rooms list</h2>
    <% if @flat.num_rooms > @flat.rooms.count %>
      <%= link_to '+ CREATE NEW ROOM', new_user_flat_room_path(@user_id, @flat_id), class: "btn btn_form width_180 fright font" %>
    <% end %>
  </div>

  <div class= "col-md-8 col-md-offset-2 bg_color">
    <ul>
      <% @rooms.each do |room| %>
        <li class= "max_width rooms_list m_auto fleft txt_room mb m_room">
        <p>
          <%= image_tag room.room_photo.url(:large), class: "" %>
          </br>
          Price: <strong><%= room.price %> €</strong>
        </p>

        <%= link_to 'EDIT ROOM', edit_user_flat_room_path(@user_id, @flat.id, room.id), class: "btn btn_form margin_10 mb_10 width_180"%>
        <%= link_to 'DELETE ROOM', user_flat_room_path(@user_id, @flat.id, room.id), method: :delete, class: "btn btn_form margin_10 mb_10 width_180", data: { confirm: 'Are you sure' } %>
        </li>
      <% end %>
    </ul>

  </div>
</div>

app/views/site/home.html.erb
<nav class="nav-general nav-home">
  <div class="ml">
    <a href="/" class="hamb fleft"><img src="assets/hamburguer.png" alt="Hamburguer menu" class="hamb"></a>
  </div>
  <div class="centrado">
    <a href="/" class="">
      <img src="assets/logo_roommate.png" alt="Logo Hotel" class="logo" >
    </a>
  </div>

  <div class="menu_right">
    <%= link_to 'SIGNUP', new_user_path, class: "btn btn_box  btn_intro fright fri2" %>
    <%= link_to 'LOGIN', new_user_path, class: "btn btn_box btn_intro fright" %>
  </div>
</nav>

<main>
  <section class="intro intro_bg">
    <div class="center_intro">
      <img src="assets/logo_roommate.png" alt="Logo Hotel" class="logo" >
      <p class="subtitle">A new way to find an apartment that perfectly matches with you! Try it!</p>
      <div class="m_auto intro_btn">
        <%= link_to 'FIND YOUR PERFECT ROOM', match_show_path, class: "btn btn_intro fleft" %>
        <%= link_to 'FIND YOUR PERFECT RENTER', match_show_path, class: "btn  btn_intro fleft m_left" %>
      </div>
    </div>
    <p class= "scroll">SCROLL TO LEARN HOW IT WORKS </br>V</p>
  </section>

  <section class="how_works">
    <p class= "vcenter"> HOW IT WORKS </p>
  </section>
</main>

app/views/users/_form.html.erb
<div class= "bg_color padd_20">
  <%= form_for @user do |f| %>
    <%= f.text_field :name, placeholder: 'Write your Name' , class: "form-control" %>
    <br />
    <%= f.text_field :email, placeholder: 'Write your Email' ,class: "form-control" %>
    <br />
    <%= f.label :avatar %> (optinal)
    <%= f.file_field :avatar, class: "form-control" %>
    <br />
    <%= f.submit 'SIGN UP', class: "btn btn_form btn-lg btn-block" %>
  <% end %>
</div>

app/views/users/_user_list_element.html.erb
<li>
 <%= user_list_element.name %>
 <%= user_list_element.email %>
 <%= user_list_element.avatar %>

 <%= link_to('Delete', user_path(user_list_element.id), method: :delete, data: { confirm: 'Are you sure' }) %>
</li>

app/views/users/edit.html.erb
<h2 class= "bg_new_color arrow arrow-s desc"> Edit User </h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>
	User list
</h1>

<ul> <% @users.each do |user| %>
	<%= render 'user_list_element', user_list_element: user %>
	<% end %>
</ul>

<br/>
<%= link_to 'new user', new_user_path %>

app/views/users/new.html.erb
<h2 class= "bg_new_color arrow arrow-s desc"> Create a New User </h2>
<%= render 'form' %>

app/views/users/show.html.erb
<h2 class= "bg_new_color arrow arrow-s desc">
	User information
</h2>
<div class="bg_color padd_20">
	<ul> <%= image_tag @user.avatar.url(:large), class: "img-circle mb_10" %>
		<li>Name: <strong><%= @user.name %></strong> </li>
		<li>Email: <strong><%= @user.email %></strong> </li>
	</ul>

	<div class="opciones">
		<%= link_to 'EDIT USER', edit_user_path(@user.id), class: "btn btn_form mb_10 width_202" %>
		<%= link_to 'CREATE A FLAT', new_user_flat_path(@user.id), class: "btn btn_form mb_10 width_202" %>
		<% if @user.flat %>
			<%= link_to 'SEE YOUR FLAT', user_flat_path(@user.id, @user.flat.id), class: "btn btn_form mb_10 width_202" %>
		<%end%>
		<%= link_to 'FIND YOUR MATCH', match_show_path, class: "btn btn_form width_202" %>
	</div>
</div>